# netlify.toml — Fidelior PDF Manager (static frontend + Netlify Functions)

[build]
  command   = ""                     # kein Build-Schritt
  publish   = "."                    # Root veröffentlichen
  functions = "netlify/functions"    # Functions-Verzeichnis

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  # Falls Functions JSON/Assets aus dem Repo brauchen (Adressbuch etc.):
  included_files = ["config/**"]     # <— entfernen, wenn nicht benötigt

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# -------- Redirects --------
# Bequemer API-Pfad: /api/... -> /.netlify/functions/...
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# -------- Caching-Strategie --------
# HTML nie cachen → Updates sofort sichtbar
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

# JS/CSS nicht hart cachen (auch in Unterordnern)
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/**/*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/**/*.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Assets-Ordner explizit (falls dort JS/CSS/JSON liegen)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# JSON IMMER FRISCH (Dropdowns etc. nie stale)
[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/**/*.json"
  [headers.values]
    Cache-Control = "no-store"

# Optional: PDF.js Worker nicht hart cachen (falls lokal gehostet)
[[headers]]
  for = "/pdf.worker.min.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
